name: Claude PR Review

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  code-review:
    # Run on PR events, or when someone comments "@claude review" on a PR
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' && 
        github.event.issue.pull_request && 
        contains(github.event.comment.body, '@claude review'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Run Claude Code Review
        uses: pylesoft/claude-code-review-action@master
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
